import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './photo-layout.css';
import './motion.css';

type View='home'|'stay'|'menu'|'events'|'gallery'|'about'|'location'|'contact'|'book'|'admin';
const ASSET='/images/green-park/';
const photos={hero:`${ASSET}hero-evening.webp`,accommodation:`${ASSET}accommodation.webp`,lounge:`${ASSET}lounge.webp`,garden:`${ASSET}garden.webp`,signboard:`${ASSET}signboard.webp`};
const nav:{id:View;label:string}[]=[
 {id:'home',label:'Home'},{id:'stay',label:'Stay'},{id:'menu',label:'Dining'},{id:'events',label:'Events'},
 {id:'gallery',label:'Gallery'},{id:'about',label:'About'},{id:'location',label:'Location'},{id:'contact',label:'Contact'}
];
const featureData=[
 {title:'Accommodation',copy:'A calm, comfortable place to stay in Njoro.',tone:'room',image:photos.accommodation,target:'stay'},
 {title:'Grill & Lounge',copy:'A relaxed setting for dining and time together.',tone:'dining',image:photos.lounge,target:'menu'},
 {title:'Grounds & Gatherings',copy:'A green setting for celebrations, meetings and gatherings.',tone:'events',image:photos.garden,target:'events'}
];
function WelcomeScreen(){return <div className="welcome-screen" aria-label="Welcome to Green Park Hotel"><div className="welcome-core"><div className="welcome-mark">G</div><p className="welcome-name">GREEN PARK</p><p className="welcome-sub">HOTEL · NJORO</p><div className="welcome-line-loader"><span/></div></div></div>}
function Brand(){return <button className="brand" onClick={()=>window.location.hash='home'}><span className="brand-mark">G</span><span><b>GREEN PARK</b><small>HOTEL · NJORO</small></span></button>}
function App(){
 const [view,setView]=useState<View>(()=>(window.location.hash.replace('#','') as View)||'home');
 const [menuOpen,setMenuOpen]=useState(false); const [booked,setBooked]=useState(false); const [admin,setAdmin]=useState(false);
 const go=(v:View)=>{setView(v);setMenuOpen(false);setBooked(false);window.location.hash=v;window.scrollTo({top:0,behavior:'smooth'});};
 React.useEffect(()=>{const fn=()=>setView((window.location.hash.replace('#','') as View)||'home');window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 const page=useMemo(()=>view==='admin'||admin?<Admin onBack={()=>{setAdmin(false);go('home')}}/>:<Public view={view} go={go} booked={booked} setBooked={setBooked}/>,[view,admin,booked]);
 return <><WelcomeScreen/><div className="welcome-line"><span>GREEN PARK HOTEL</span><span>NJORO · KENYA</span></div><header><Brand/><nav className={menuOpen?'open':''}>{nav.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>go(n.id)}>{n.label}</button>)}<button className="nav-book" onClick={()=>go('book')}>Book / Enquire</button></nav><button className="menu-button" onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?'Close':'Menu'}</button></header>{page}<footer><div><Brand/><p>A refined digital front door for Green Park Hotel, Njoro.</p></div><div className="footer-links"><button onClick={()=>go('stay')}>Stay</button><button onClick={()=>go('menu')}>Dining</button><button onClick={()=>go('events')}>Events</button><button onClick={()=>go('gallery')}>Gallery</button><button onClick={()=>setAdmin(true)}>Admin preview</button></div></footer></>;
}
function Public({view,go,booked,setBooked}:{view:View;go:(v:View)=>void;booked:boolean;setBooked:(v:boolean)=>void}){
 if(view==='home')return <Home go={go}/>; if(view==='book')return <Booking booked={booked} setBooked={setBooked}/>;
 const titles:Record<string,[string,string]>={stay:['Stay at Green Park','Accommodation designed around comfort and simplicity.'],menu:['Green Park Grill & Lounge','A warm setting for meals, conversation and relaxed time together.'],events:['Events at Green Park','A flexible space for gatherings, celebrations and meetings.'],gallery:['A glimpse of Green Park','Explore the hotel, grounds, dining and atmosphere.'],about:['A hotel experience built around place','A clean digital front door for Green Park Hotel in Njoro.'],location:['Find Green Park','Njoro · Sobea Road'],contact:['Contact Green Park','Start an enquiry without requiring a guest account.']};
 const [title,sub]=titles[view]||titles.about;
 return <main className="page"><section className="page-head reveal-up"><span className="eyebrow">GREEN PARK · NJORO</span><h1>{title}</h1><p>{sub}</p></section>
 {view==='stay'&&<section className="content-grid"><article className="photo-card hover-lift reveal-up"><div className="photo-space" style={{backgroundImage:`url(${photos.accommodation})`}}><span>GREEN PARK</span></div><div className="card-copy"><span className="eyebrow">STAY</span><h2>Accommodation</h2><p>Comfortable spaces presented clearly, with guest enquiries kept simple.</p><button onClick={()=>go('book')}>Plan a stay →</button></div></article><article className="photo-card hover-lift reveal-up delay-1"><div className="photo-space" style={{backgroundImage:`url(${photos.lounge})`}}><span>GREEN PARK</span></div><div className="card-copy"><span className="eyebrow">DINE</span><h2>Grill & Lounge</h2><p>Bring dining, lounge and hospitality into the same guest journey.</p><button onClick={()=>go('menu')}>Explore dining →</button></div></article></section>}
 {view==='menu'&&<section className="visual-content"><div className="wide-photo reveal-image" style={{backgroundImage:`url(${photos.lounge})`}}/><section className="menu-intro"><span className="eyebrow">THE DINING EXPERIENCE</span><h2>Green Park Grill & Lounge</h2><p>A visual menu experience ready for the hotel's approved dishes, descriptions and prices.</p><div className="menu-categories"><article><span>01</span><h3>Breakfast & light bites</h3><p>Present morning options and lighter choices with clear descriptions.</p></article><article><span>02</span><h3>Lunch & grill</h3><p>Give the core menu its own strong, easy-to-scan presentation.</p></article><article><span>03</span><h3>Drinks & lounge</h3><p>Showcase drinks, lounge favourites and seasonal updates.</p></article></div><button className="dark-button" onClick={()=>go('book')}>Ask about dining →</button></section></section>}
 {view==='events'&&<section className="visual-content"><div className="wide-photo reveal-image" style={{backgroundImage:`url(${photos.garden})`}}/><section className="event-feature"><div><span className="eyebrow">GATHER · MEET · CELEBRATE</span><h2>Events with Green Park</h2><p>The website is ready for staff to publish event dates, venues, descriptions and booking enquiries from the admin area.</p></div><div className="event-options"><span>Celebrations</span><span>Meetings</span><span>Gatherings</span></div><button className="dark-button" onClick={()=>go('book')}>Plan an event →</button></section></section>}
 {view==='gallery'&&<section className="gallery-grid">{[photos.hero,photos.accommodation,photos.lounge,photos.garden,photos.signboard].map((src,i)=><div className={`gallery-tile g${i+1} hover-lift reveal-image`} key={src} style={{backgroundImage:`url(${src})`}}><span>{['Evening exterior','Accommodation','Grill & Lounge','Garden','Green Park sign'][i]}</span></div>)}</section>}
 {view==='about'&&<section className="about-visual"><div className="about-photo reveal-image" style={{backgroundImage:`url(${photos.signboard})`}}/><div className="about-copy reveal-up"><span className="eyebrow">THE PLACE</span><h2>Green Park, clearly presented.</h2><p>The visual identity of this review build is grounded in the real property, its greenery, accommodation and Grill & Lounge setting.</p><button className="text-button" onClick={()=>go('location')}>Find the hotel →</button></div></section>}
 {view==='location'&&<section className="split"><div className="location-card reveal-image"><div className="location-photo" style={{backgroundImage:`url(${photos.signboard})`}}/><div className="location-overlay"><span>GREEN PARK HOTEL</span><small>Njoro – Sobea Road</small></div></div><div className="location-copy reveal-up"><span className="eyebrow">LOCATION</span><h2>Easy to reach. Easy to remember.</h2><p>Use the live map link for directions to Green Park Hotel in Njoro.</p><a className="dark-button location-link" href="https://maps.app.goo.gl/VkHBGPQhcguYocoYA" target="_blank" rel="noreferrer">Get directions →</a></div></section>}
 {view==='contact'&&<Booking booked={booked} setBooked={setBooked} compact/>}</main>;
}
function Home({go}:{go:(v:View)=>void}){return <main><section className="hero"><div className="hero-visual"><div className="hero-photo reveal-image" style={{backgroundImage:`url(${photos.hero})`}}><span>GREEN PARK HOTEL · NJORO</span></div></div><div className="hero-copy"><span className="eyebrow reveal-up">WELCOME TO GREEN PARK HOTEL</span><h1 className="reveal-up delay-1">Stay close to what matters.</h1><p className="reveal-up delay-2">A welcoming digital front door for Green Park Hotel in Njoro — calm, useful and rooted in the real property.</p><div className="hero-actions reveal-up delay-3"><button className="dark-button" onClick={()=>go('book')}>Book / Enquire</button><button className="text-button" onClick={()=>go('stay')}>Explore the hotel →</button></div></div></section><section className="intro"><span className="eyebrow">THE EXPERIENCE</span><h2>Stay. Dine. Gather. Explore.</h2><p>One clear journey from discovering the hotel to making an enquiry.</p></section><section className="feature-strip">{featureData.map(r=><button key={r.title} className="feature hover-lift" onClick={()=>go(r.target as View)}><span className="feature-photo" style={{backgroundImage:`url(${r.image})`}}></span><span><small>GREEN PARK</small><b>{r.title}</b><em>{r.copy}</em></span><i>↗</i></button>)}</section><section className="home-cta"><div><span className="eyebrow">YOUR NEXT VISIT</span><h2>Make your enquiry in a few steps.</h2><p>No guest account required.</p></div><button className="dark-button" onClick={()=>go('book')}>Start an enquiry →</button></section></main>}
function Booking({booked,setBooked,compact=false}:{booked:boolean;setBooked:(v:boolean)=>void;compact?:boolean}){return <section className={compact?'booking compact page':'booking page'}><div className="page-head"><span className="eyebrow">GUEST ENQUIRY</span><h1>{booked?'Request received':'Plan your stay'}</h1><p>{booked?'Reference GP-REVIEW-001 · presentation flow.':'No guest account is required. Send the hotel your preferred date and contact details.'}</p></div>{booked?<div className="confirmation"><span className="check">✓</span><h2>Your enquiry is ready.</h2><p>The production version will route this request into the hotel admin workflow.</p><button className="dark-button" onClick={()=>setBooked(false)}>Create another enquiry</button></div>:<form onSubmit={e=>{e.preventDefault();setBooked(true)}}><div><label>Name<input required placeholder="Your name"/></label><label>Phone<input required placeholder="+254 …"/></label></div><div><label>Email <em>optional</em><input type="email" placeholder="you@example.com"/></label><label>Preferred date<input type="date" required/></label></div><label>What can we help with?<select><option>Accommodation</option><option>Dining</option><option>Event / meeting</option><option>General enquiry</option></select></label><label>Message<textarea rows={4} placeholder="Tell the hotel what you need…"/></label><button className="dark-button" type="submit">Send enquiry →</button></form>}</section>}
function Admin({onBack}:{onBack:()=>void}){const [tab,setTab]=useState('Overview');const tabs=['Overview','Rooms','Menu','Events','Gallery','Bookings','Enquiries','Content'];return <main className="admin-shell"><aside><div className="admin-brand"><span className="brand-mark">G</span><b>GREEN PARK</b><small>ADMIN PREVIEW</small></div>{tabs.map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}<button onClick={onBack}>← Back to website</button></aside><section className="admin-main"><div className="admin-top"><div><span className="eyebrow">CONTROL ROOM</span><h1>{tab}</h1></div><span className="status-pill">DEMO DATA OFF</span></div>{tab==='Overview'?<><div className="stat-grid">{[['Bookings','0'],['Enquiries','0'],['Events','Ready'],['Content','Ready']].map(([a,b])=><div className="stat" key={a}><span>{a}</span><b>{b}</b><small>Production data connects later</small></div>)}</div><div className="admin-panel"><h2>Quick actions</h2><div className="quick-grid">{['Add room','Add menu item','Create event','Upload gallery'].map(x=><button key={x} onClick={()=>setTab(x.includes('gallery')?'Gallery':x.includes('event')?'Events':x.includes('menu')?'Menu':'Rooms')}>{x}<span>+</span></button>)}</div></div></>:<div className="admin-panel"><span className="eyebrow">{tab.toUpperCase()}</span><h2>{tab} management</h2><p>Information architecture is ready for production CRUD and database persistence.</p><div className="admin-table"><div><b>Records</b><span>0</span></div><div><b>Status</b><span>Ready for production connection</span></div><div><b>Actions</b><span>Add · Edit · Publish</span></div></div></div>}</section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
