import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';
import './photo-layout.css';

type View = 'home'|'stay'|'menu'|'events'|'gallery'|'about'|'location'|'contact'|'book'|'admin';
const ASSET='/images/green-park/';
const photos={hero:`${ASSET}hero-evening.webp`, accommodation:`${ASSET}accommodation.webp`, lounge:`${ASSET}lounge.webp`, garden:`${ASSET}garden.webp`, signboard:`${ASSET}signboard.webp`};
const nav:{id:View;label:string}[]=[
 {id:'home',label:'Home'},{id:'stay',label:'Stay'},{id:'menu',label:'Menu'},{id:'events',label:'Events'},
 {id:'gallery',label:'Gallery'},{id:'about',label:'About'},{id:'location',label:'Location'},{id:'contact',label:'Contact'}
];
const featureData=[
 {title:'Accommodation',copy:'A calm, comfortable place to stay in Njoro.',tone:'room',image:photos.accommodation,target:'stay'},
 {title:'Dining',copy:'Explore the Green Park Grill & Lounge experience.',tone:'dining',image:photos.lounge,target:'menu'},
 {title:'Grounds & Events',copy:'A flexible setting for gatherings, celebrations and meetings.',tone:'events',image:photos.garden,target:'events'}
];
function Brand(){return <button className="brand" onClick={()=>window.location.hash='home'}><span className="brand-mark">G</span><span><b>GREEN PARK</b><small>HOTEL · NJORO</small></span></button>}
function App(){
 const [view,setView]=useState<View>(()=>(window.location.hash.replace('#','') as View)||'home');
 const [menuOpen,setMenuOpen]=useState(false); const [booked,setBooked]=useState(false); const [admin,setAdmin]=useState(false);
 const go=(v:View)=>{setView(v);setMenuOpen(false);setBooked(false);window.location.hash=v;window.scrollTo({top:0,behavior:'smooth'});};
 React.useEffect(()=>{const fn=()=>setView((window.location.hash.replace('#','') as View)||'home');window.addEventListener('hashchange',fn);return()=>window.removeEventListener('hashchange',fn)},[]);
 const page=useMemo(()=>view==='admin'||admin?<Admin onBack={()=>{setAdmin(false);go('home')}}/>:<Public view={view} go={go} booked={booked} setBooked={setBooked}/>,[view,admin,booked]);
 return <><div className="welcome-line"><span>GREEN PARK HOTEL</span><span>NJORO · KENYA</span></div><header><Brand/><nav className={menuOpen?'open':''}>{nav.map(n=><button key={n.id} className={view===n.id?'active':''} onClick={()=>go(n.id)}>{n.label}</button>)}<button className="nav-book" onClick={()=>go('book')}>Book / Enquire</button></nav><button className="menu-button" onClick={()=>setMenuOpen(v=>!v)}>{menuOpen?'Close':'Menu'}</button></header>{page}<footer><div><Brand/><p>A presentation prototype for review. Production services, database and secure admin infrastructure remain the next phase.</p></div><div className="footer-links"><button onClick={()=>go('stay')}>Stay</button><button onClick={()=>go('menu')}>Dining</button><button onClick={()=>go('gallery')}>Gallery</button><button onClick={()=>setAdmin(true)}>Admin preview</button></div></footer></>;
}
function Public({view,go,booked,setBooked}:{view:View;go:(v:View)=>void;booked:boolean;setBooked:(v:boolean)=>void}){
 if(view==='home')return <Home go={go}/>; if(view==='book')return <Booking booked={booked} setBooked={setBooked}/>;
 const titles:Record<string,[string,string]>={stay:['Stay at Green Park','Accommodation designed around comfort and simplicity.'],menu:['Green Park Grill & Lounge','A visual menu space ready for approved hotel content.'],events:['Events at Green Park','Create, publish and update upcoming experiences from one place.'],gallery:['A glimpse of Green Park','The review build now uses the supplied Green Park photography set.'],about:['A hotel experience built around place','A clean digital front door for Green Park Hotel in Njoro.'],location:['Find Green Park','Njoro · Sobea Road'],contact:['Contact Green Park','Start an enquiry without requiring a guest account.']};
 const [title,sub]=titles[view]||titles.about;
 return <main className="page"><section className="page-head"><span className="eyebrow">GREEN PARK · NJORO</span><h1>{title}</h1><p>{sub}</p></section>
 {view==='stay'&&<section className="content-grid">{featureData.slice(0,2).map(r=><article className={`photo-card ${r.tone}`} key={r.title}><div className="photo-space" style={{backgroundImage:`url(${r.image})`}}><span>GREEN PARK</span></div><div className="card-copy"><span className="eyebrow">GREEN PARK</span><h2>{r.title}</h2><p>{r.copy}</p><button onClick={()=>go('book')}>Enquire →</button></div></article>)}</section>}
 {view==='menu'&&<section className="visual-content"><div className="wide-photo" style={{backgroundImage:`url(${photos.lounge})`}}/><ContentBlocks labels={['Breakfast & light bites','Lunch & grill','Drinks & lounge']}/></section>}
 {view==='events'&&<section className="visual-content"><div className="wide-photo" style={{backgroundImage:`url(${photos.garden})`}}/><EmptyState title="No upcoming events published yet" text="Once hotel event information is approved, staff can publish it here from the admin area." action={()=>setView('admin')}/></section>}
 {view==='gallery'&&<section className="gallery-grid">{[photos.hero,photos.accommodation,photos.lounge,photos.garden,photos.signboard].map((src,i)=><div className={`gallery-tile g${i+1}`} key={src} style={{backgroundImage:`url(${src})`}}><span>{['Evening exterior','Accommodation','Grill & Lounge','Garden','Green Park sign'][i]}</span></div>)}</section>}
 {view==='about'&&<section className="about-visual"><div className="about-photo" style={{backgroundImage:`url(${photos.signboard})`}}/><div className="about-copy"><span className="eyebrow">THE PLACE</span><h2>Green Park, clearly presented.</h2><p>The signboard and grounds are part of the visual identity of this review build, connecting the digital experience to the real property.</p></div></section>}
 {view==='location'&&<section className="split"><div className="map-card"><div className="map-grid"><span>GREEN PARK HOTEL</span><small>Njoro – Sobea Road</small></div></div><div><span className="eyebrow">LOCATION</span><h2>Close to Njoro, easy to find.</h2><p>Green Park Hotel is presented here with a dedicated location section for map directions, contact details and future local SEO content.</p><button className="dark-button" onClick={()=>go('contact')}>Ask for directions →</button></div></section>}
 {view==='contact'&&<Booking booked={booked} setBooked={setBooked} compact/>}</main>;
}
function Home({go}:{go:(v:View)=>void}){return <main><section className="hero"><div className="hero-visual"><div className="hero-photo" style={{backgroundImage:`url(${photos.hero})`}}><span>GREEN PARK HOTEL · NJORO</span></div></div><div className="hero-copy"><span className="eyebrow">WELCOME TO GREEN PARK HOTEL</span><h1>Stay close to what matters.</h1><p>A modern digital front door for Green Park Hotel in Njoro — calm, welcoming and built around the real hotel experience.</p><div className="hero-actions"><button className="dark-button" onClick={()=>go('book')}>Book / Enquire</button><button className="text-button" onClick={()=>go('stay')}>Explore the hotel →</button></div></div></section><section className="intro"><span className="eyebrow">THE EXPERIENCE</span><h2>One place for stays, dining, events and enquiries.</h2><p>Real Green Park photography now leads the presentation instead of blank placeholders.</p></section><section className="feature-strip">{featureData.map(r=><button key={r.title} className="feature" onClick={()=>go(r.target as View)}><span className={`feature-photo ${r.tone}`} style={{backgroundImage:`url(${r.image})`}}></span><span><small>GREEN PARK</small><b>{r.title}</b></span><i>↗</i></button>)}</section><section className="review-band"><div><span className="eyebrow">DESIGNED FOR REVIEW</span><h2>Premium presentation now. Production depth next.</h2></div><button className="light-button" onClick={()=>go('about')}>See the concept →</button></section></main>}
function ContentBlocks({labels}:{labels:string[]}){return <section className="list-section">{labels.map((x,i)=><article key={x}><span>0{i+1}</span><div><h2>{x}</h2><p>Approved hotel content will live here. This structure is ready for dynamic content and future database connection.</p></div></article>)}</section>}
function EmptyState({title,text,action}:{title:string;text:string;action:()=>void}){return <section className="empty"><span className="empty-line"></span><h2>{title}</h2><p>{text}</p><button className="dark-button" onClick={action}>Open admin preview →</button></section>}
function Booking({booked,setBooked,compact=false}:{booked:boolean;setBooked:(v:boolean)=>void;compact?:boolean}){return <section className={compact?'booking compact page':'booking page'}><div className="page-head"><span className="eyebrow">GUEST ENQUIRY</span><h1>{booked?'Request received':'Plan your stay'}</h1><p>{booked?'Reference GP-REVIEW-001 · prototype confirmation only.':'No guest account is required. Send the hotel your preferred dates and contact details.'}</p></div>{booked?<div className="confirmation"><span className="check">✓</span><h2>Your enquiry is ready.</h2><p>The final production version will send this request into the secure hotel admin workflow.</p><button className="dark-button" onClick={()=>setBooked(false)}>Create another enquiry</button></div>:<form onSubmit={e=>{e.preventDefault();setBooked(true)}}><div><label>Name<input required placeholder="Your name"/></label><label>Phone<input required placeholder="+254 …"/></label></div><div><label>Email <em>optional</em><input type="email" placeholder="you@example.com"/></label><label>Preferred date<input type="date" required/></label></div><label>What can we help with?<select><option>Accommodation</option><option>Dining</option><option>Event / meeting</option><option>General enquiry</option></select></label><label>Message<textarea rows={4} placeholder="Tell the hotel what you need…"/></label><button className="dark-button" type="submit">Send enquiry →</button></form>}</section>}
function Admin({onBack}:{onBack:()=>void}){const [tab,setTab]=useState('Overview');const tabs=['Overview','Rooms','Menu','Events','Gallery','Bookings','Enquiries','Content'];return <main className="admin-shell"><aside><div className="admin-brand"><span className="brand-mark">G</span><b>GREEN PARK</b><small>ADMIN PREVIEW</small></div>{tabs.map(t=><button className={tab===t?'selected':''} key={t} onClick={()=>setTab(t)}>{t}</button>)}<button onClick={onBack}>← Back to website</button></aside><section className="admin-main"><div className="admin-top"><div><span className="eyebrow">CONTROL ROOM</span><h1>{tab}</h1></div><span className="status-pill">REVIEW PROTOTYPE</span></div>{tab==='Overview'?<><div className="stat-grid">{[['Bookings','0'],['Enquiries','0'],['Events','Not published'],['Content','Ready']].map(([a,b])=><div className="stat" key={a}><span>{a}</span><b>{b}</b><small>Real data connects in production phase</small></div>)}</div><div className="admin-panel"><h2>Quick actions</h2><div className="quick-grid">{['Add room','Add menu item','Create event','Upload gallery'].map(x=><button key={x} onClick={()=>setTab(x.includes('gallery')?'Gallery':x.includes('event')?'Events':x.includes('menu')?'Menu':'Rooms')}>{x}<span>+</span></button>)}</div></div></>:<div className="admin-panel"><span className="eyebrow">{tab.toUpperCase()}</span><h2>{tab} management is mapped.</h2><p>This review surface demonstrates the information architecture without inventing live hotel data. Production CRUD, authentication and database persistence are reserved for the next phase.</p><div className="empty-admin">No live {tab.toLowerCase()} records yet.</div></div>}</section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
